### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by hanm2019** [CMU-SAFARI/ramulator#101]
after I compiled the source code with `make -j`
./ramulator configs/DDR3-config.cfg --mode-dram dram.trace 
Segmentation fault (core dumped)

**Comment by arthasSin** [comment]
Note that you have to type '=' between '--mode' and 'dram', but not '-'
`./ramulator configs/DDR3-config.cfg --mode=dram dram.trace`

**Comment by fengsy97** [comment]
I have this problem too

**Comment by fengsy97** [comment]
I solved this by deleting the empty line in config file. The config read progress can't tolerate empty lines.

**Comment by hanm2019** [comment]
:)
