### ISSUE TITLE
Error while using Trace Generator tool in Ramulator

### ISSUE THREAD

**Issue by Upasna55** [CMU-SAFARI/ramulator#116]
Hello All

I need to use trace generator tool in ramulator. Since, pin3.7 is not available now, so I've tried using pin versions `3.11, 3.22, and 3.25`, but I am getting the following error:
![Screenshot from 2022-11-05 22-33-44](https://user-images.githubusercontent.com/91068864/200132528-c20fcd83-b529-41c4-b39d-d796720376c4.png)
Quite possibly this seems to be a compiler compatibility issue. I am using `Ubuntu 20.04`, `Perl 5.30.0`, `gcc 9.4.0`. If you could help me in setting up trace generator, I would be so grateful.
 
Thanks & Regards
Upasna

**Comment by ChenNie99** [comment]
Pintools 3.7 download link:

https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.7-97619-g0d0c92f4f-gcc-linux.tar.gz

hope this helps you

**Comment by Upasna55** [comment]
Yes Chen Nie, it worked. Thanks a lot. 
I need one more help. If you're using `vscode`, do you get `incomplete type` values of local variables while debugging Ramulator with `gdb`? If so, can you please share your configuration for appropriate debugging.  

Thanks & Regards
Upasna

**Comment by Upasna55** [comment]
Yes Chen Nie, it worked. Thanks a lot.

Best Regards
Upasna
