### ISSUE TITLE
Problem with Ramulator.

### ISSUE THREAD

**Issue by greenmeent** [CMU-SAFARI/ramulator#15]
To use ramulator.
I followed README.md

---------------------------------------------------------------------------------------------------------
*Memory trace Driven*
$ cd ramulator
$ make -j
$ ./ramulator configs/DDR3-config.cfg --mode=dram dram.trace (here is problem)
---------------------------------------------------------------------------------------------------------

~/ramulator$ ls
configs    dram.trace                         LICENSE   plot.py    test_ddr3.py
cpu.trace  gem5-0e86fac7254c-ramulator.patch  Makefile  README.md  test_spec.py
cputraces  gem5-stable

~/ramulator$ ./ramulator configs/DDR3-config.cfg --mode=dram dram.trace
-bash: ./ramulator: No such file or directory

what should I do? Please help me~

**Comment by i7mist** [comment]
Hi greenmeent,

I think your folder is incomplete. Could you try to clone it again? (It seems you even don't have src/ ...)

Thanks,
Tianshi

**Comment by greenmeent** [comment]
thanks, Tianshi!!!!

I solve this problem but there is another problem....


./ramulator configs/DDR3-config.cfg --mode=cpu cpu.trace
ramulator: src/Config.cpp:43: void ramulator::Config::parse(const string &): Assertion `tokens.size() == 2 && "Only allow two tokens in one line"' failed.


What should I do? please

**Comment by i7mist** [comment]
I think you may not use the latest version. Could you try to run "git pull" and make sure the last commit is "Update configs"?

Thanks,
Tianshi

**Comment by zhizunbaowhy** [comment]
Hi,
I have the same problem.

./ramulator configs/DDR3-config.cfg --mode=cpu cpu.trace
ramulator: src/Config.cpp:43: void ramulator::Config::parse(const string &): Assertion `tokens.size() == 2 && "Only allow two tokens in one line"' failed.

I'm using the latest version. And I've already run "git pull". 
What should I do?
I would appreciate it if you could help me with the issue.
