### ISSUE TITLE
0 Value in Simulation Output

### ISSUE THREAD

**Issue by bugubugu123** [CMU-SAFARI/ramulator#16]
Hi,
Under the latest version (7b50b644654885e92d6a742b05d2a065784ffd6b) of Ramulator, I started the simulation by "./ramulator configs/DDR3-config.cfg --mode=cpu cputraces/429.mcf". However, in the output, I found several "0" values (some are shown below) which seemed not reasonable.

> ramulator.read_latency_avg_0	0.000000
ramulator.read_latency_sum_0	1276331318
ramulator.req_queue_length_avg_0	0.000000
ramulator.req_queue_length_sum_0	2147122205
ramulator.read_req_queue_length_avg_0	0.000000
ramulator.read_req_queue_length_sum_0	1276340988 
ramulator.write_req_queue_length_avg_0	0.000000 
ramulator.write_req_queue_length_sum_0	870781217

Could you help check whether those "0" values are correct or not?

Thanks a lot!

**Comment by i7mist** [comment]
Hi bugubugu123,

Thanks for helping us find this bug! This is because the finalization function for controller is not called. A patch to fix this will be pushed soon.

Tianshi
