### ISSUE TITLE
Failed to compile with Gem5

### ISSUE THREAD

**Issue by ShawnLess** [CMU-SAFARI/ramulator#20]
I have cloned the Gem5 and reverted to the version 10231, and patched the gem5.

But when I try to compile the gem5, it also prompt  following error:

 [    LINK]  -> ARM/gem5.opt
Undefined symbols for architecture x86_64:
  "ramulator::ALDRAM::aldram_timing(ramulator::ALDRAM::Temp)", referenced from:
      ramulator::Controller<ramulator::ALDRAM>::update_temp(ramulator::ALDRAM::Temp) in libramulator.a(Controller.os)
  "ramulator::TLDRAM::standard_name", referenced from:
      ramulator::Controller<ramulator::TLDRAM>::issue_cmd(ramulator::TLDRAM::Command, std::__1::vector<int, std::__1::allocator<int> > const&) in libramulator.a(Controller.os)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [build/ARM/gem5.opt] Error 1
scons: building terminated because of errors.

I have tried different architectures in building gem5, such as "scons build/x86/gem5.opt" and "scons build/ARM/gem5.opt", the same error occurs.

Following is my OS and GCC configuration:
--
shawnlessdeMacBook-Pro:src shawnless$ uname -a
Darwin shawnlessdeMacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

--
shawnlessdeMacBook-Pro:src shawnless$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
shawnlessdeMacBook-Pro:src shawnless$ 

Any suggestion ?

**Comment by i7mist** [comment]
Hi ShawnLess,

Try to add the following lines in `ext/ramulator/SConscript` after `DRAMFile('WideIO2.cpp')`
``` c++
DRAMFile('TLDRAM.cpp')
DRAMFile('ALDRAM.cpp')
```

I believe this can fix your problem.

BTW, I'm curious whether you did any modification to ramulator source code before compile it with gem5?

Thanks,
Tianshi

**Comment by ShawnLess** [comment]
Great!  This fixed the problem pretty well.  Thanks.
I haven't done any modification to the source code. I just follow the instructions as on github.
