### ISSUE TITLE
Don't Support Read/Write Value ?

### ISSUE THREAD

**Issue by ShawnLess** [CMU-SAFARI/ramulator#24]
Hi all:
I have just inspected few codes of Ramulator, just want to confirm does Ramulator track the read/write value ?  The entry in dram.trace only contains address and read/write commands.

**Comment by i7mist** [comment]
No we don't. It's just a timing model.

**Comment by ShawnLess** [comment]
Oh, but if Ramulator doesn't track the read/write value,  when it used by the gem5, where the actual load/store value come from ?

Does it instantiate another memory to hold the read/write value while the Ramulator handle the timing ?

**Comment by i7mist** [comment]
Yes you're right. Gem5 treats the data storage and DRAM timing model separately.

**Comment by ShawnLess** [comment]
Great! Thanks~~~~.
