### ISSUE TITLE
DRAM<T>:::update_timing() code

### ISSUE THREAD

**Issue by ShawnLess** [CMU-SAFARI/ramulator#25]
When I was inspecting code of DRAM.h, I was confused with DRAM.h:356 and DRAM.h:375. It says 

 __for (auto& t : timing[int(cmd)]) {__

but __timing__ is a private member of DRAM which is initialized in constructor with

__timing = spec->timing[int(level)];__

Where __spec->timing__ is a two dimensional data for all Spec.  So DRAM.timing is a vector and DRAM.timing[ int(cmd)] is a single structure, not a vector. 

Why the DRAM<T>::update_timing() uses the __for__ clause to traverse this scalar object ?

**Comment by i7mist** [comment]
timing is a three dimensional data structure. For example, see the definition in `src/DDR3.h`:
```c++
     vector<TimingEntry> timing[int(Level::MAX)][int(Command::MAX)];
```
And you can read `init_timing` function in `src/DDR3.cpp` to see how this structure is instantiated

**Comment by ShawnLess** [comment]
Oh, yes. Got it. Thanks. :+1:
