### ISSUE TITLE
Can ramulator affect the simulation time in Gem5?

### ISSUE THREAD

**Issue by bugubugu123** [CMU-SAFARI/ramulator#8]
Except the ramulator part, I have run the Gem5 twice with the same configurations. But surprisingly, the simulation times ( "sim_seconds" in stats.txt ) are exactly the same. Did I miss anything or has the ramulator wired the timing mechanism to Gem5?

How have I run Gem5?
./gem5.opt configs/example/se.py --mem-type=ramulator --mem-size=2MB --ramulator-config=gem5-config1.cfg --caches --l2cache -c [my_executable]

./gem5.opt configs/example/se.py --mem-type=ramulator --mem-size=2MB --ramulator-config=gem5-config2.cfg --caches --l2cache -c [my_executable]

For config1.cfg:
 standard = WideIO
 channels = 4
 ranks = 1
 speed = WideIO_266
 org = WideIO_8Gb

For config2.cfg:
 standard = DDR3
 channels = 4
 ranks = 1
 speed = DDR3_1600K
 org = DDR3_4Gb_x8

Thanks a lot in advance!

**Comment by i7mist** [comment]
Hi, I can see the sim_seconds statistics changing during my experiment using ramulator.  And I guess your problem is because you didn't specify the option --cpu-type=detailed for se.py, so it is simulated in atomic mode, which will not use cycle accurate ramulator for simulation.
