### ISSUE TITLE
Problem in MemoryFactory<T>::create()

### ISSUE THREAD

**Issue by bugubugu123** [CMU-SAFARI/ramulator#9]
Hi,

I am using Gem5+Ramulator. When one Gem5Wrapper object is created, the corresponding MemoryFactory<T>::create() will be called.  When T is WideIO2, this function is specialized by MemoryFactory<WideIO2>::create() implemented in MemoryFactory.cpp (line 35).

The weird thing is, when running Gem5, if I configure ramulator as WideIO2, it still uses the most general template (MemoryFactory.h line 52) instead of the specialized one. However, I go back to the standalone ramulator and add a main() which only initialize a Gem5Wrapper with WideIO2, which correctly uses the specialized one. Could you check whether you have the same problem? If I am the only one who has the problem, could you give me some clue to resolve it?

I just use the default compile setting, my gcc version is 4.8.3 and clang version is 3.6.2

Thanks a lot!

**Comment by i7mist** [comment]
Thanks for this feedback. You can fix this problem by adding the following declaration at the beginning of src/Gem5Wrapper.cpp.
```c++
template <>
MemoryBase *MemoryFactory<WideIO2>::create(const Config& configs, int cacheline);
template <>
MemoryBase *MemoryFactory<SALP>::create(const Config& configs, int cacheline);
```
Patches to fix this problem will be pushed soon.
